#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
merge_slide.py - Merge a single-slide PPTX (generated by PptxGenJS) back into
an unpacked PPTX directory at a specific slide position.

This enables the Preview -> Confirm -> Merge workflow for precise single-page
editing of existing presentations.

Usage:
    python merge_slide.py <source.pptx> <target_unpacked_dir> <slide_number>

Example:
    python merge_slide.py slides_preview/slide-03.pptx unpacked/ 3
"""

import os
import sys
import shutil
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

RELS_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
CT_NS = "http://schemas.openxmlformats.org/package/2006/content-types"


def extract_pptx(pptx_path: str, dest_dir: str):
    """Unpack a PPTX zip archive."""
    with zipfile.ZipFile(pptx_path, "r") as zf:
        zf.extractall(dest_dir)


def next_free_rid(rels_path: Path) -> int:
    """Return the next free rId number inside a single .rels file."""
    if not rels_path.exists():
        return 1
    tree = ET.parse(str(rels_path))
    root = tree.getroot()
    max_id = 0
    for rel in root.findall(f".//{{{RELS_NS}}}Relationship"):
        rid = rel.get("Id", "")
        if rid.startswith("rId"):
            try:
                max_id = max(max_id, int(rid[3:]))
            except ValueError:
                pass
    return max_id + 1


def merge_slide(source_pptx: str, target_dir: str, slide_number: int):
    source_pptx = Path(source_pptx).resolve()
    target_dir = Path(target_dir).resolve()
    tmp_dir = Path(os.environ.get("TEMP", "/tmp")) / "merge_slide_src"

    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    tmp_dir.mkdir(parents=True, exist_ok=True)

    # 1. Unpack source (should contain exactly one slide: slide1.xml)
    extract_pptx(str(source_pptx), str(tmp_dir))

    src_slide_xml = tmp_dir / "ppt" / "slides" / "slide1.xml"
    src_rels_xml = tmp_dir / "ppt" / "slides" / "_rels" / "slide1.xml.rels"

    if not src_slide_xml.exists():
        print("Error: source PPTX does not contain ppt/slides/slide1.xml")
        sys.exit(1)

    tgt_slide_dir = target_dir / "ppt" / "slides"
    tgt_rels_dir = tgt_slide_dir / "_rels"
    tgt_media_dir = target_dir / "ppt" / "media"

    tgt_slide_xml = tgt_slide_dir / f"slide{slide_number}.xml"
    tgt_rels_xml = tgt_rels_dir / f"slide{slide_number}.xml.rels"

    # 2. Copy slide XML
    shutil.copy2(str(src_slide_xml), str(tgt_slide_xml))

    # 3. Process relationships: copy media, avoid filename collisions, rewrite rIds
    if src_rels_xml.exists():
        tree = ET.parse(str(src_rels_xml))
        root = tree.getroot()

        # Existing media filenames in target to avoid collisions
        existing_media = set()
        if tgt_media_dir.exists():
            existing_media = set(os.listdir(tgt_media_dir))

        # Next free rId inside the target rels file
        free_rid = next_free_rid(tgt_rels_xml)

        for rel in root.findall(f".//{{{RELS_NS}}}Relationship"):
            target_attr = rel.get("Target", "")
            rel_type = rel.get("Type", "")

            if "image" in rel_type and target_attr.startswith("../media/"):
                media_name = os.path.basename(target_attr)
                src_media_path = tmp_dir / "ppt" / "media" / media_name

                final_name = media_name
                if final_name in existing_media:
                    base, ext = os.path.splitext(final_name)
                    counter = 1
                    while final_name in existing_media:
                        final_name = f"{base}_{counter}{ext}"
                        counter += 1

                if src_media_path.exists():
                    tgt_media_dir.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(str(src_media_path), str(tgt_media_dir / final_name))
                    existing_media.add(final_name)

                rel.set("Target", f"../media/{final_name}")

            # Assign a fresh rId to every relationship in the new rels file
            rel.set("Id", f"rId{free_rid}")
            free_rid += 1

        # Write out the new rels file
        tgt_rels_dir.mkdir(parents=True, exist_ok=True)
        tree.write(str(tgt_rels_xml), xml_declaration=True, encoding="UTF-8")
    else:
        # Source has no rels: if target already had one, it becomes stale.
        # Remove stale rels to avoid broken references.
        if tgt_rels_xml.exists():
            tgt_rels_xml.unlink()

    # 4. Ensure [Content_Types].xml knows about this slide
    ct_path = target_dir / "[Content_Types].xml"
    if ct_path.exists():
        ct_tree = ET.parse(str(ct_path))
        ct_root = ct_tree.getroot()

        part_name = f"/ppt/slides/slide{slide_number}.xml"
        found = False
        for override in ct_root.findall(f".//{{{CT_NS}}}Override"):
            if override.get("PartName") == part_name:
                found = True
                break

        if not found:
            override = ET.SubElement(
                ct_root,
                f"{{{CT_NS}}}Override",
            )
            override.set("PartName", part_name)
            override.set(
                "ContentType",
                "application/vnd.openxmlformats-officedocument.presentationml.slide+xml",
            )
            ct_tree.write(str(ct_path), xml_declaration=True, encoding="UTF-8")

    # 5. Cleanup
    shutil.rmtree(tmp_dir)
    print(f"Success: merged slide into {tgt_slide_xml}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <source.pptx> <target_unpacked_dir> <slide_number>")
        sys.exit(1)

    merge_slide(sys.argv[1], sys.argv[2], int(sys.argv[3]))
